version: "3"
services:

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:1.6
    restart: always
    volumes:
      - "./mosquitto/data:/mosquitto/data"
      - "./mosquitto/log:/mosquitto/log"
    ports:
      - "1883:1883"
      - "9001:9001"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.14.3
    restart: always
    devices:
      - "/dev/ttyAMA1:/dev/ttyAMA1"
    environment:
      TZ: "Europe/Berlin"
      # DEBUG: "z*"
    volumes:
      - "./zigbee2mqtt:/app/data"
      - "/run/udev:/run/udev:ro"

  zigbee2mqtt-assistant:
    container_name: z2ma
    image: carldebilly/zigbee2mqttassistant:0.3.176
    restart: always
    environment:
      Z2MA_SETTINGS__MQTTSERVER: "mosquitto"
      TZ: "Europe/Berlin"
    ports:
      - "8124:80"

  homeassistant:
    container_name: homeassistant
    image: homeassistant/raspberrypi4-homeassistant:0.114.3
    restart: always
    environment:
      TZ: "Europe/Berlin"
    volumes:
      - "./homeassistant:/config"
    ports:
      - "8123:8123"

  nodered:
    container_name: nodered
    image: nodered/node-red:1.1.3-minimal
    restart: always
    environment:
      TZ: "Europe/Berlin"
    volumes:
      - "./nodered:/data"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "1880:1880"

