version: "3"
services:

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - "./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.29.2
    restart: always
    devices:
      - "/dev/ttyAMA0:/dev/ttyAMA0"
    environment:
      TZ: "Europe/Berlin"
      # DEBUG: "z*"
    volumes:
      - "./zigbee2mqtt:/app/data"
      - "/run/udev:/run/udev:ro"
    environment:
      VIRTUAL_HOST: "z2m.tatooine"
      VIRTUAL_PORT: "8080"

  zigbee2mqtt-assistant:
    container_name: z2ma
    image: carldebilly/zigbee2mqttassistant:0.3.181-linux-arm32
    restart: always
    environment:
      Z2MA_SETTINGS__MQTTSERVER: "mosquitto"
      TZ: "Europe/Berlin"
      VIRTUAL_HOST: "z2ma.tatooine"

  homeassistant:
    container_name: homeassistant
    image: homeassistant/raspberrypi4-homeassistant:2023.1.4
    restart: always
    environment:
      TZ: "Europe/Berlin"
      VIRTUAL_HOST: "ha.tatooine"
      VIRTUAL_PORT: "8123"
    volumes:
      - "./homeassistant:/config"

  appdaemon:
    # should wait for HASS to run
    container_name: appdaemon
    image: acockburn/appdaemon:4.2.1
    restart: always
    env_file: appdaemon/.env
    environment:
      HASS_URL: "http://homeassistant:8123"
      MQTT_CLIENT: "mosquitto"
      TZ: "Europe/Berlin"
    volumes:
      - "./appdaemon/conf:/conf"

networks:
  default:
    external:
      name: nginx-proxy

