version: "3"
services:

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:1.6
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "./mosquitto/data:/mosquitto/data"
      - "./mosquitto/log:/mosquitto/log"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.16.2
    restart: always
    devices:
      - "/dev/ttyAMA1:/dev/ttyAMA1"
    environment:
      TZ: "Europe/Berlin"
      # DEBUG: "z*"
    ports:
      - "8080:8080"
    volumes:
      - "./zigbee2mqtt:/app/data"
      - "/run/udev:/run/udev:ro"

  zigbee2mqtt-assistant:
    container_name: z2ma
    image: carldebilly/zigbee2mqttassistant:0.3.178
    restart: always
    environment:
      Z2MA_SETTINGS__MQTTSERVER: "mosquitto"
      TZ: "Europe/Berlin"
    ports:
      - "8124:80"

  homeassistant:
    container_name: homeassistant
    image: homeassistant/raspberrypi4-homeassistant:2021.1.4
    restart: always
    environment:
      TZ: "Europe/Berlin"
    volumes:
      - "./homeassistant:/config"
    ports:
      - "8123:8123"

  appdaemon:
    # should wait for HASS to run
    container_name: appdaemon
    image: pixelplastic/rpi-appdaemon:4.0.5
    restart: always
    env_file: appdaemon/.env
    environment:
      HASS_URL: "http://homeassistant:8123"
      MQTT_CLIENT: "mosquitto"
      TZ: "Europe/Berlin"
    volumes:
      - "./appdaemon/conf:/conf"
