version: "3"
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:1.6
    restart: always
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.12.0
    restart: always
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    environment:
      TZ: "Europe/Berlin"
      # DEBUG: "*"
    volumes:
      - ./zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro

  zigbee2mqtt-assistant:
    container_name: z2ma
    image: carldebilly/zigbee2mqttassistant:0.3.154
    restart: always
    environment:
      - Z2MA_SETTINGS__MQTTSERVER=mosquitto
      #- Z2MA_SETTINGS__MQTTUSERNAME={MQTTUSERNAME}
      #- Z2MA_SETTINGS__MQTTPASSWORD={MQTTPASSWORD}
      # Set to your TimeZone when using on Linux https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      # Won't work if you're using the Windows version of the container
      - TZ=Europe/Berlin
    ports:
      - "8880:80"

#  homeassistant:
#    container_name: homeassistant
#    image: homeassistant/raspberrypi4-homeassistant:0.106.6
#    restart: always
#    environment:
#      TZ: "Europe/Berlin"
#    volumes:
#      - ./homeassistant:/config
#    ports:
#      - "8123:8123"
