version: "3"
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:1.6
    restart: always
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.12.2
    restart: always
    devices:
      - "/dev/ttyAMA1:/dev/ttyAMA1"
    environment:
      TZ: "Europe/Berlin"
      # DEBUG: "z*"
    volumes:
      - "./zigbee2mqtt:/app/data"
      - "/run/udev:/run/udev:ro"

  zigbee2mqtt-assistant:
    container_name: z2ma
    image: carldebilly/zigbee2mqttassistant:0.3.156
    restart: always
    environment:
      - Z2MA_SETTINGS__MQTTSERVER=mosquitto
      - TZ=Europe/Berlin
    ports:
      - "8124:80"

  homeassistant:
    container_name: homeassistant
    image: homeassistant/raspberrypi4-homeassistant:0.108.3
    restart: always
    environment:
      TZ: "Europe/Berlin"
    volumes:
      - ./homeassistant:/config
    ports:
      - "8123:8123"

  appdaemon:
    container_name: appdaemon
    build: ./appdaemon/src
    restart: always
    environment:
      HA_URL: "http://homeassistant:8123"
      TOKEN: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI2OTRhYWQzZTU5NzE0MDJiOTczNzhlYjgyNGMxNjA1YiIsImlhdCI6MTU4NjcyNzUzNCwiZXhwIjoxOTAyMDg3NTM0fQ.KAIkInbCeKXirW576nw2x3v1rVOpU7xabhcGH9UTtoQ"
      DASH_URL: "http://r2d2:5050"
      TZ: "Europe/Berlin"
    volumes:
      - "./appdaemon/conf:/conf"
    ports:
      - "5050:5050"
