version: "3"
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:1.6
    restart: always
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.12.0
    restart: always
    devices:
      - "/dev/ttyAMA1:/dev/ttyAMA1"
    environment:
      TZ: "Europe/Berlin"
      # DEBUG: "*"
    volumes:
      - "./zigbee2mqtt:/app/data"
      - "/run/udev:/run/udev:ro"

  homeassistant:
    container_name: homeassistant
    image: homeassistant/raspberrypi4-homeassistant:0.105.4
    restart: always
    environment:
      TZ: "Europe/Berlin"
    volumes:
      - ./homeassistant:/config
    ports:
      - "8123:8123"
