default_config:

lovelace:
  mode: yaml
  resources:
    - type: module
      url: /local/zigbee2mqtt-networkmap.js?v=0.7.0
      # see: https://github.com/azuwis/zigbee2mqtt-networkmap
    - type: module
      url: /local/mini-graph-card-bundle.js?v=0.9.4
      # see: https://github.com/kalkih/mini-graph-card

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.24.0.0/24
  ip_ban_enabled: false
  login_attempts_threshold: 5

tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml
frontend:
  themes: !include themes.yaml

#mqtt:
#  discovery: true
#  broker: mosquitto
#  birth_message:
#    topic: 'hass/status'
#    payload: 'online'
#  will_message:
#    topic: 'hass/status'
#    payload: 'offline'

input_boolean:
  appdaemon_movie_mode:
    name: Movie Mode
    initial: off
    icon: "mdi:projector"
  appdaemon_fan_mode:
    name: Hushbox Fan Mode
    initial: off
    icon: "mdi:fan"
input_number:
  appdaemon_fan_speed:
    name: Hushbox Fan Speed
    initial: 20
    min: 20
    max: 30
    step: 1

stream:
camera:
  - platform: mjpeg
    name: OctoPrint
    still_image_url: http://k-2so/webcam/?action=snapshot
    mjpeg_url: http://k-2so/webcam/?action=stream

speedtestdotnet:
  # server_id: 11519 # see: http://www.speedtestserver.com/
  scan_interval:
    minutes: 360
  monitored_conditions:
    - ping
    - download
    - upload

influxdb:
  host: r2d2.fritz.box
  port: 8086
  database: homeassistant
  # max_retries: 3
  default_measurement: state
