default_config:

http:
  base_url: r2d2:8123
lovelace:
  mode: yaml
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml
frontend:
  themes: !include themes.yaml

mqtt:
  discovery: true
  broker: mosquitto
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

speedtestdotnet:
  # server_id: 11519 # see: http://www.speedtestserver.com/
  scan_interval:
    minutes: 360
  monitored_conditions:
    - ping
    - download
    - upload
