default_config:

lovelace:
  mode: yaml
  resources:
    - type: module
      url: /local/zigbee2mqtt-networkmap.js?v=0.7.0 # see: https://github.com/azuwis/zigbee2mqtt-networkmap/releases
    - type: module
      url: /local/mini-graph-card-bundle.js?v=0.11.0 # see: https://github.com/kalkih/mini-graph-card/releases
    - type: module
      url: /local/slider-entity-row.js?v=17.2.1 # see: https://github.com/thomasloven/lovelace-slider-entity-row/releases
    - type: module
      url: /local/button-card@3.4.2.js # see https://github.com/custom-cards/button-card/releases

  dashboards:
    lovelace-lms:
      mode: yaml
      filename: ui-lms.yaml
      title: Media Server
      icon: mdi:cast-audio
    lovelace-3dprint:
      mode: yaml
      filename: ui-3d-printing.yaml
      title: 3D-Printing
      icon: mdi:printer-3d
      show_in_sidebar: true
      require_admin: true
    lovelace-zigbee:
      mode: yaml
      filename: ui-zigbee.yaml
      title: Zigbee
      icon: mdi:zigbee
      show_in_sidebar: true
      require_admin: true

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.24.0.0/24
  ip_ban_enabled: false
  login_attempts_threshold: 5

tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
frontend:
  themes: !include themes.yaml
  extra_module_url:
    - /local/card-mod@3.2.0.js

mqtt:
  sensor:
    - name: Zigbee2mqtt Networkmap
      # if you change base_topic of Zigbee2mqtt, change state_topic accordingly
      state_topic: zigbee2mqtt/bridge/networkmap/raw
      value_template: >-
        {{ now().strftime('%Y-%m-%d %H:%M:%S') }}
      # again, if you change base_topic of Zigbee2mqtt, change json_attributes_topic accordingly
      json_attributes_topic: zigbee2mqtt/bridge/networkmap/raw

input_boolean:
  appdaemon_movie_mode:
    name: Movie Mode
    initial: off
    icon: "mdi:projector"
  appdaemon_fan_mode:
    name: Hushbox Fan Mode
    initial: off
    icon: "mdi:fan"

  appdaemon_light_group_hall:
    name: Light Group Hall
    initial: off
    icon: "mdi:lightbulb-group"
  appdaemon_light_group_living:
    name: Light Group Living
    initial: off
    icon: "mdi:lightbulb-group"
  appdaemon_light_group_kitchen:
    name: Light Group Kitchen
    initial: off
    icon: "mdi:lightbulb-group"
  appdaemon_light_group_bath:
    name: Light Group Bath
    initial: off
    icon: "mdi:lightbulb-group"
  appdaemon_light_group_sleep:
    name: Light Group Sleep
    initial: off
    icon: "mdi:lightbulb-group"
  appdaemon_light_group_work:
    name: Light Group Work
    initial: off
    icon: "mdi:lightbulb-group"

input_number:
  appdaemon_fan_speed:
    name: Hushbox Fan Speed
    initial: 20
    min: 20
    max: 30
    step: 1
input_button:
  kitchen_power_hifi:
    name: Hifi Power
    icon: mdi:radio

stream:
# camera:
#   - platform: mjpeg
#     name: OctoPrint
#     still_image_url: http://k-2so/webcam/?action=snapshot
#     mjpeg_url: http://k-2so/webcam/?action=stream

speedtestdotnet:
  # server_id: 11519 # see: http://www.speedtestserver.com/
  scan_interval:
    minutes: 360
  monitored_conditions:
    - ping
    - download
    - upload

influxdb:
  host: 192.168.178.3 # r2d2.fritz.box
  port: 8086
  database: homeassistant
  # max_retries: 3
  default_measurement: state
