title: Tatooine Smart Home
views:
  - title: Home
    path: home
    badges:
      - entity: binary_sensor.updater
      - entity: person.marcel_hoyer
      - entity: sun.sun
    cards:
      - type: vertical-stack
        cards:
          - title: Wohnzimmer
            icon: mdi:sofa
            type: entities
            entities:
              - entity: light.living_light_ceiling
                name: Decke
                icon: mdi:ceiling-light
                type: custom:slider-entity-row
                toggle: true
              - entity: light.living_basket_light
                name: Korblampe
                icon: mdi:lamp
                type: custom:slider-entity-row
                toggle: true
              - entity: switch.living_power_switch_fairy_lights
                name: Licherkette
                icon: mdi:string-lights
              - entity: light.living_party_uplight
                name: Party Deckenfluter
                icon: mdi:floor-lamp-torchiere
                type: custom:slider-entity-row
                toggle: true
          - type: entities
            entities:
              - entity: input_boolean.appdaemon_movie_mode
                name: Movie Mode
                icon: mdi:theater
              - type: weblink
                name: Kodi (c3po)
                url: http://c3po:8080/
                icon: mdi:web

          - title: Flur
            icon: mdi:shoe-sneaker
            type: entities
            state_color: true
            show_header_toggle: false
            entities:
              - entity: input_boolean.appdaemon_light_group_hall
                name: Decke

          - title: Bad
            icon: mdi:shower
            type: entities
            entities:
              - entity: input_boolean.appdaemon_light_group_bath
                name: Decke
              - entity: light.bath_mirror_light
                name: Licht Badspiegel
                icon: mdi:mirror
                type: custom:slider-entity-row
                toggle: true

      - type: vertical-stack
        cards:
          - title: Küche
            icon: mdi:silverware-fork-knife
            type: entities
            entities:
              - entity: light.kitchen_light
                name: Decke
                icon: mdi:ceiling-light
                type: custom:slider-entity-row
                toggle: true
              - entity: light.kitchen_light_corner
                name: Eckschrank
                icon: mdi:lamp
                type: custom:slider-entity-row
                toggle: true
              - entity: light.kitchen_wireless_control_driver
                name: Arbeitsplatte
                icon: mdi:lightbulb-fluorescent-tube-outline
                type: custom:slider-entity-row
                toggle: true
              - entity: switch.power_switch_01
                name: Sternchen
                icon: mdi:string-lights
          - type: entities
            entities:
              - entity: input_button.kitchen_power_hifi
                name: Stereoanlage Küche
              - type: weblink
                name: Logitech Media Server
                url: /lovelace-lms
                icon: mdi:web

          - title: Schlafzimmer
            icon: mdi:bed
            type: entities
            entities:
              - entity: switch.sleep_power_switch_fairy_lights
                name: Licherkette
                icon: mdi:string-lights
              - entity: light.sleep_light
                name: Decke
                icon: mdi:ceiling-light
                type: custom:slider-entity-row
                toggle: true
              - type: divider
              - entity: cover.sleep_blinds_left
                name: Schlafzimmerrollo (links)
              - entity: cover.sleep_blinds_right
                name: Schlafzimmerrollo (rechts)

      - type: vertical-stack
        cards:
          - type: weather-forecast
            entity: weather.home
          - type: history-graph
            title: 'Speedtest'
            hours_to_show: 48
            refresh_interval: 0
            entities:
              - entity: sensor.speedtest_download
                name: Download
              - entity: sensor.speedtest_upload
                name: Upload
          - type: entities
            entities:
              - sensor.speedtest_ping
              - type: button
                name: Reload Lovelace
                tap_action:
                  action: call-service
                  service: lovelace.reload_resources

  - title: Wohnzimmer
    path: living
    icon: mdi:sofa
    cards:
      - type: vertical-stack
        cards:
        - title: Licht
          icon: mdi:lightbulb
          type: entities
          entities:
            - entity: light.living_light_ceiling
              name: Decke
              icon: mdi:ceiling-light
              type: custom:slider-entity-row
              toggle: true
            - entity: light.living_basket_light
              name: Korblampe
              icon: mdi:lamp
              type: custom:slider-entity-row
              toggle: true
            - entity: switch.living_power_switch_fairy_lights
              name: Licherkette
              icon: mdi:string-lights
            - entity: light.living_party_uplight
              name: Party Deckenfluter
              icon: mdi:floor-lamp-torchiere
              type: custom:slider-entity-row
              toggle: true
            - entity: light.living_ball_light
              name: Das Ball
              icon: mdi:crystal-ball
              type: custom:slider-entity-row
              toggle: true
      - type: vertical-stack
        cards:
        - title: Kino
          icon: mdi:theater
          type: entities
          show_header_toggle: false
          entities:
            - entity: input_boolean.appdaemon_movie_mode
              name: Movie Mode
            - entity: input_boolean.appdaemon_fan_mode
              name: Hushbox Fan
            - entity: input_number.appdaemon_fan_speed
              name: Hushbox Fan Speed

        - type: horizontal-stack
          cards:
            - type: "custom:button-card"
              icon: mdi:volume-minus
              size: 30px
              tap_action:
                action: call-service
                service: mqtt.publish
                data:
                  topic: hushboxfancontrol/send_ir_codes
                  payload: o 0x5EA1D827 0x5EA1D827 0xFFFFFFFFFFFFFFFF 0xFFFFFFFFFFFFFFFF
            - type: "custom:button-card"
              icon: mdi:volume-plus
              size: 30px
              tap_action:
                action: call-service
                service: mqtt.publish
                service_data:
                  topic: hushboxfancontrol/send_ir_codes
                  payload: o 0x5EA158A7 0x5EA158A7 0xFFFFFFFFFFFFFFFF 0xFFFFFFFFFFFFFFFF

      - type: vertical-stack
        cards:
          - type: iframe
            aspect_ratio: 100%
            url: http://lms.tatooine

      - type: vertical-stack
        cards:
        - type: custom:mini-graph-card
          height: 60
          font_size: 60
          lower_bound: 0
          upper_bound: 100
          line_width: 2
          entities:
            - entity: sensor.living_switch_battery
              name: Living Switch

  - title: Küche
    path: kitchen
    icon: mdi:silverware-fork-knife
    cards:
      - type: vertical-stack
        cards:
        - title: Licht
          type: entities
          icon: mdi:lightbulb
          entities:
            - entity: light.kitchen_light
              name: Decke
              icon: mdi:ceiling-light
              type: custom:slider-entity-row
              toggle: true
            - entity: light.kitchen_light_corner
              name: Eckschrank
              icon: mdi:lamp
              type: custom:slider-entity-row
              toggle: true
            - entity: light.kitchen_wireless_control_driver
              name: Arbeitsplatte
              icon: mdi:lightbulb-fluorescent-tube-outline
              type: custom:slider-entity-row
              toggle: true
            - entity: switch.power_switch_01
              name: Sternchen
              icon: mdi:string-lights

        - title: Coffee
          type: entities
          icon: mdi:coffee-outline
          entities:
            - entity: switch.kitchen_xenia
              name: Xenia
              icon: mdi:coffee-maker-outline
              toggle: true
            - entity: sensor.kitchen_xenia_energy
              name: Xenia Energy
            - entity: switch.kitchen_df64
              name: DF64 Grinder
              icon: mdi:cog
              toggle: true
            - entity: sensor.kitchen_df64_energy
              name: DF64 Energy

      - type: vertical-stack
        cards:
        - title: Audio
          type: entities
          icon: mdi:silverware-fork-knife
          entities:
            - entity: input_button.kitchen_power_hifi
              name: Stereoanlage

        - type: iframe
          aspect_ratio: 100%
          url: http://lms.tatooine

      - type: vertical-stack
        cards:
        - type: custom:mini-graph-card
          height: 100
          font_size: 60
          lower_bound: 0
          upper_bound: 100
          line_width: 2
          entities:
            - entity: sensor.kitchen_env_temperature
              name: Temperatur
        - type: custom:mini-graph-card
          height: 100
          font_size: 60
          lower_bound: 0
          upper_bound: 100
          line_width: 2
          entities:
            - entity: sensor.kitchen_env_humidity
              name: Luftfeuchtigkeit
        - type: custom:mini-graph-card
          height: 100
          font_size: 100
          lower_bound: 0
          upper_bound: 100
          line_width: 2
          entities:
            - entity: sensor.kitchen_switch_battery
              name: Kitchen Switch
            - entity: sensor.kitchen_env_battery
              name: Env Sensor

  - title: Schlafzimmer
    path: sleep
    icon: mdi:bed
    cards:
      - type: vertical-stack
        cards:
        - title: Licht
          type: entities
          icon: mdi:lightbulb
          entities:
            - entity: switch.sleep_power_switch_fairy_lights
              name: Licherkette
              icon: mdi:string-lights
            - entity: light.sleep_light
              name: Decke
              type: custom:slider-entity-row
              toggle: true
      - title: Rollos
        type: entities
        icon: mdi:gauge
        entities:
            - entity: cover.sleep_blinds_left
              name: Schlafzimmerrollo (links)
            - entity: cover.sleep_blinds_right
              name: Schlafzimmerrollo (rechts)
      - title: Heizung
        type: entities
        icon: mdi:home-thermometer-outline
        entities:
            - entity: climate.sleep_thermostat
              name: Thermostat
      - title: Sensoren
        type: entities
        icon: mdi:gauge
        entities:
            - entity: sensor.sleep_env_temperature
              name: Temperatur
            - entity: sensor.sleep_env_humidity
              name: Luftfeuchtigkeit
            - entity: sensor.sleep_env_pressure
              name: Luftdruck
            - entity: sensor.sleep_blinds_left_battery
              name: Schlafzimmerrollo (links)
            - entity: sensor.sleep_blinds_right_battery
              name: Schlafzimmerrollo (rechts)
      - type: vertical-stack
        cards:
        - type: custom:mini-graph-card
          height: 100
          font_size: 100
          lower_bound: 0
          upper_bound: 100
          line_width: 2
          entities:
            - entity: sensor.sleep_switch_battery
              name: Light Switch
              show_state: true
            - entity: sensor.sleep_blinds_ctrl_01_battery
              name: Blinds Ctrl 01
              show_state: true
            - entity: sensor.sleep_blinds_ctrl_02_battery
              name: Blinds Ctrl 02
              show_state: true

  - title: Bad
    path: bath
    icon: mdi:shower
    cards:
      - type: vertical-stack
        cards:
        - title: Licht
          icon: mdi:lightbulb
          type: entities
          entities:
            - entity: light.bath_light_01
              name: Dusche
              icon: mdi:lightbulb-spot
              type: custom:slider-entity-row
              toggle: true
            - entity: light.bath_light_02
              name: Eingang
              icon: mdi:lightbulb-spot
              type: custom:slider-entity-row
              toggle: true
            - entity: light.bath_light_03
              name: Waschbecken
              icon: mdi:lightbulb-spot
              type: custom:slider-entity-row
              toggle: true
            - entity: light.bath_light_04
              name: Wanne
              icon: mdi:lightbulb-spot
              type: custom:slider-entity-row
              toggle: true
            - type: divider
            - entity: light.bath_mirror_light
              name: Spiegel
              type: custom:slider-entity-row
              toggle: true

      - title: Sensoren
        type: entities
        icon: mdi:gauge
        entities:
          - entity: sensor.bath_env_temperature
            name: Temperatur
          - entity: sensor.bath_env_humidity
            name: Luftfeuchtigkeit
          - entity: sensor.bath_env_pressure
            name: Luftdruck
          - entity: sensor.bath_motion_illuminance_lux
            name: Helligkeit
          - entity: binary_sensor.bath_motion_occupancy
            name: Besetzt?
      - type: vertical-stack
        cards:
        - type: custom:mini-graph-card
          height: 100
          font_size: 60
          lower_bound: 0
          upper_bound: 100
          line_width: 2
          entities:
            - entity: sensor.bath_switch_battery
              name: Light Switch Battery

  - title: Flur
    path: hall
    icon: mdi:shoe-sneaker
    cards:
      - type: vertical-stack
        cards:
        - title: Licht
          icon: mdi:lightbulb
          type: entities
          show_header_toggle: true
          entities:
            - entity: light.hall_light_01
              name: Eingang
              icon: mdi:lightbulb-spot
              type: custom:slider-entity-row
              toggle: true
            - entity: light.hall_light_02
              name: Mitte
              icon: mdi:lightbulb-spot
              type: custom:slider-entity-row
              toggle: true
            - entity: light.hall_light_03
              name: Hinten
              icon: mdi:lightbulb-spot
              type: custom:slider-entity-row
              toggle: true
      - type: vertical-stack
        cards:
        - type: custom:mini-graph-card
          height: 100
          font_size: 60
          lower_bound: 0
          upper_bound: 100
          line_width: 2
          entities:
            - entity: sensor.hall_switch_01_battery
              name: Hall Switch 01
            - entity: sensor.hall_switch_02_battery
              name: Hall Switch 02
            - entity: sensor.hall_door_sensor_battery
              name: Door Sensor

  - title: Arbeitszimmer
    path: work
    icon: mdi:briefcase
    cards:
      - type: vertical-stack
        cards:
        - title: WiFi
          type: entities
          show_header_toggle: true
          entities:
            # - entity: switch.work_ethernet_switch
            #   name: Cisco Ethernet Switch
            #   icon: mdi:ethernet
            - entity: switch.work_uap
              name: UniFi Access Point
              icon: mdi:access-point
        - title: Drucker
          type: entities
          show_header_toggle: false
          entities:
            - entity: switch.work_laser_printer_switch
              name: Drucker (HP-LaserJet-P2015dn)
              icon: mdi:printer
            - entity: switch.work_3d_printer_switch
              name: 3D-Drucker
              icon: mdi:printer-3d
      - title: Heizung
        type: entities
        icon: mdi:home-thermometer-outline
        entities:
            - entity: climate.work_thermostat
              name: Thermostat
      - title: Sensoren
        type: entities
        icon: mdi:gauge
        entities:
          - entity: sensor.work_env_temperature
            name: Temperatur
      - type: vertical-stack
        cards:
        - type: custom:mini-graph-card
          height: 100
          font_size: 60
          lower_bound: 0
          upper_bound: 100
          line_width: 2
          entities:
            - entity: sensor.work_env_battery
              name: Env Sensor Battery

