version: "3"
services:

  appdaemon:
    container_name: appdaemon
    image: acockburn/appdaemon:4.0.5
    env_file: .env
    environment:
      HASS_URL: "http://r2d2:8123"
      MQTT_CLIENT: "r2d2"
      TZ: "Europe/Berlin"
    volumes:
      - "./conf:/conf"
    ports:
      - "5050:5050"
