version: "3"
services:

  appdaemon:
    container_name: appdaemon
    image: acockburn/appdaemon:4.1.0
    env_file: .env
    environment:
      HASS_URL: "http://192.168.178.3:8123"
      MQTT_CLIENT: "192.168.178.3"
      TZ: "Europe/Berlin"
    volumes:
      - "./conf:/conf"
    ports:
      - "5050:5050"
