homeassistant: false 
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://mosquitto'
serial:
  port: /dev/ttyACM0
  disable_led: true
advanced:
  log_level: debug
  baudrate: 115200
  report: false
# devices:
