homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://mosquitto'
serial:
  port: /dev/ttyAMA1
advanced:
  log_level: debug
  log_output:
    - console
  baudrate: 115200
  rtscts: false
  report: false
devices:
  '0x7cb03eaa00ac909d':
    friendly_name: 20200223-osram-cla60-e27-rgbw-01
  '0x7cb03eaa00aa112a':
    friendly_name: 20200223-osram-cla60-e27-rgbw-02
  '0x7cb03eaa00adacd7':
    friendly_name: 20200223-osram-cla60-e27-rgbw-03
  '0x7cb03eaa00ada7f5':
    friendly_name: 20200223-osram-cla60-e27-rgbw-04
  '0x680ae2fffe314a4e':
    friendly_name: 20200223-ikea-tradfri-e1810-remote-control-01
  '0x14b457fffe79b246':
    friendly_name: 20200228-ikea-tradfri-e1743-remote-switch-01
  '0x14b457fffe67a19c':
    friendly_name: living_room_light_ceiling
  '0xccccccfffe932c4c':
    friendly_name: living_room_switch_main
  '0x680ae2fffe1ae4e9':
    friendly_name: sleeping_room_repeater
  '0xec1bbdfffede164f':
    friendly_name: sleeping_room_blinds_control
  '0x680ae2fffe37b078':
    friendly_name: sleeping_room_blinds
