homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://mosquitto'
serial:
  port: /dev/ttyACM0
advanced:
  log_level: debug
  baudrate: 115200
  report: false
devices:
  '0x7cb03eaa00ac909d':
    friendly_name: 20200223-osram-cla60-e27-rgbw-01
  '0x7cb03eaa00aa112a':
    friendly_name: 20200223-osram-cla60-e27-rgbw-02
  '0x7cb03eaa00adacd7':
    friendly_name: 20200223-osram-cla60-e27-rgbw-03
  '0x7cb03eaa00ada7f5':
    friendly_name: 20200223-osram-cla60-e27-rgbw-04
  '0x680ae2fffe314a4e':
    friendly_name: 20200223-ikea-tradfri-e1810-remote-control-01
  '0x14b457fffe79b246':
    friendly_name: 20200228-ikea-tradfri-e1743-remote-switch-01
  '0x14b457fffe67a19c':
    friendly_name: 20200301-ikea-tradfri-led1836g9-e27
  '0x086bd7fffe3fc805':
    friendly_name: ikea-kitchen-30w-driver
