homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto
serial:
  port: /dev/ttyAMA0
frontend:
  url: http://z2m.tatooine
advanced:
  pan_id: 6755
  log_level: info
  log_output:
    - console
  baudrate: 115200
  rtscts: false
  report: false
  ikea_ota_use_test_url: true
devices:
  '0x7cb03eaa00adacd7':
    friendly_name: kitchen_light
    retain: true
  '0x14b457fffe79b246':
    friendly_name: kitchen_switch
    retain: true
  '0x00158d00041dffcf':
    friendly_name: kitchen_env
  '0x00158d0004724e85':
    friendly_name: kitchen_light_corner
    retain: true
  '0x680ae2fffe314a4e':
    friendly_name: kitchen_e1810_remote_control
  '0x086bd7fffe3fc805':
    friendly_name: kitchen_wireless_control_driver
  '0xa4c138793b6af8be':
    friendly_name: kitchen_df64
  '0xa4c138d3c19bfa83':
    friendly_name: kitchen_xenia
  '0xccccccfffe932c4c':
    friendly_name: living_switch
  '0x7cb03eaa00aa112a':
    friendly_name: living_basket_light
    retain: true
  '0x00158d0004724ead':
    friendly_name: living_ball_light
  '0x14b457fffe67a19c':
    friendly_name: living_light_ceiling
  '0x842e14fffe366622':
    friendly_name: living_power_switch_fairy_lights
  '0x00158d0004738205':
    friendly_name: living_party_uplight
  '0xa4c13857060eac49':
    friendly_name: sleep_power_switch_fairy_lights
  '0x7cb03eaa00ac909d':
    friendly_name: sleep_light
    retain: true
  '0x680ae2fffe1ae4e9':
    friendly_name: sleep_repeater
  '0xec1bbdfffede164f':
    friendly_name: sleep_blinds_ctrl_01
  '0x000d6ffffea94dd0':
    friendly_name: sleep_blinds_ctrl_02
    retain: true
  '0xd0cf5efffeea14b4':
    friendly_name: sleep_blinds_right
    retain: true
  '0x680ae2fffe37b078':
    friendly_name: sleep_blinds_left
  '0xccccccfffea2fddd':
    friendly_name: sleep_switch
    retain: true
  '0x00158d00044f7d2b':
    friendly_name: sleep_env
  '0x00158d000490fe24':
    friendly_name: sleep_balcony_door_sensor
  '0x842e14fffef154f3':
    friendly_name: sleep_thermostat
  '0x00158d000521e62c':
    friendly_name: hall_door_sensor
    retain: true
  '0xec1bbdfffe9cd801':
    friendly_name: hall_light_02
    retain: true
  '0xec1bbdfffea2ff59':
    friendly_name: hall_light_01
    retain: true
  '0xec1bbdfffe9ecc68':
    friendly_name: hall_light_03
    retain: true
  '0xccccccfffe9251f1':
    friendly_name: hall_switch_01
  '0xccccccfffe924c55':
    friendly_name: hall_switch_02
  '0xccccccfffe708788':
    friendly_name: bath_switch
    retain: true
  '0x00158d0004210e5d':
    friendly_name: bath_env
  '0x00158d00047d4108':
    friendly_name: bath_motion
  '0x7cb03eaa00ada7f5':
    friendly_name: bath_mirror_light
    retain: true
  '0xec1bbdfffe474333':
    friendly_name: bath_light_01
    retain: true
  '0xccccccfffee07b63':
    friendly_name: bath_light_02
    retain: true
  '0xec1bbdfffe4354b1':
    friendly_name: bath_light_03
    retain: true
  '0x14b457fffe5bbcb3':
    friendly_name: bath_light_04
    retain: true
  '0x842e14fffe366660':
    friendly_name: power_switch_01
  '0x00158d00041e543c':
    friendly_name: work_env
  '0x60a423fffe61dd24':
    friendly_name: work_laser_printer_switch
  '0x60a423fffe652cf6':
    friendly_name: work_3d_printer_switch
  '0xa4c1380282841053':
    friendly_name: work_uap
  '0x5c0272fffe857045':
    friendly_name: work_thermostat
  '0xa4c138487445da05':
    friendly_name: '0xa4c138487445da05'
  '0xccccccfffeb49bf7':
    friendly_name: '0xccccccfffeb49bf7'
groups:
  '1':
    friendly_name: kitchen_light_group
    retain: false
    transition: 2
    optimistic: true
    off_state: all_members_off
    devices:
      - kitchen_wireless_control_driver
ota:
  update_check_interval: 10080
