homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://mosquitto'
serial:
  port: /dev/ttyAMA1
advanced:
  log_level: debug
  log_output:
    - console
  baudrate: 115200
  rtscts: false
  report: false
devices:
  '0x7cb03eaa00aa112a':
    friendly_name: kitchen_ball_light
    retain: true
  '0x7cb03eaa00adacd7':
    friendly_name: kitchen_light
    retain: true
  '0x14b457fffe79b246':
    friendly_name: kitchen_switch
    retain: true
  '0x00158d00041dffcf':
    friendly_name: kitchen_env
  '0x14b457fffe67a19c':
    friendly_name: living_light_ceiling
  '0x00158d0004724e85':
    friendly_name: living_light_floor
    retain: true
  '0xccccccfffe932c4c':
    friendly_name: living_switch
  '0x7cb03eaa00ac909d':
    friendly_name: sleep_light
    retain: true
  '0x680ae2fffe1ae4e9':
    friendly_name: sleep_repeater
  '0xec1bbdfffede164f':
    friendly_name: sleep_blinds_ctrl_01
  '0x000d6ffffea94dd0':
    friendly_name: sleep_blinds_ctrl_02
    retain: true
  '0xd0cf5efffeea14b4':
    friendly_name: sleep_blinds_right
    retain: true
  '0x680ae2fffe37b078':
    friendly_name: sleep_blinds_left
  '0xccccccfffea2fddd':
    friendly_name: sleep_switch
    retain: true
  '0x00158d00044f7d2b':
    friendly_name: sleep_env
  '0xec1bbdfffe9cd801':
    friendly_name: hall_light_02
    retain: true
  '0xec1bbdfffea2ff59':
    friendly_name: hall_light_01
    retain: true
  '0xec1bbdfffe9ecc68':
    friendly_name: hall_light_03
    retain: true
  '0xccccccfffe9251f1':
    friendly_name: hall_switch_01
  '0xccccccfffe924c55':
    friendly_name: hall_switch_02
  '0xccccccfffe708788':
    friendly_name: bath_switch
    retain: true
  '0x00158d0004210e5d':
    friendly_name: bath_env
  '0x00158d00047d4108':
    friendly_name: bath_motion
  '0x7cb03eaa00ada7f5':
    friendly_name: bath_mirror_light
    retain: true
  '0xec1bbdfffe474333':
    friendly_name: bath_light_01
    retain: true
  '0xccccccfffee07b63':
    friendly_name: bath_light_02
    retain: true
  '0xec1bbdfffe4354b1':
    friendly_name: bath_light_03
    retain: true
  '0x14b457fffe5bbcb3':
    friendly_name: bath_light_04
    retain: true
  '0x00158d00041e543c':
    friendly_name: work_env
  '0x680ae2fffe314a4e':
    friendly_name: 20200223-ikea-tradfri-e1810-remote-control-01
  '0x00158d000521e62c':
    friendly_name: hall_door_sensor
    retain: true
